### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by valdirmendesdev** [koemaeda/abap-json#2]
Hello @koemaeda, how are you?

I'm Brazilian and I want to contribute to the project. Do you accept?

Thanks for your project.

==================================================
Que legal cara, vi que você é brasileiro! Gostaria de contribuir com o projeto, posso?

**Comment by koemaeda** [comment]
Opa! Claro que aceito!

**Comment by valdirmendesdev** [comment]
Show de bola man! Forkei o projeto e vou iniciar as contribuições para mandar as pull requests! Valeu man
